# Generated by Django 4.1.2 on 2022-10-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saya',
            name='github',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saya',
            name='instagram',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saya',
            name='linkedin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saya',
            name='twitter',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
