# Generated by Django 4.1.2 on 2022-10-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_saya_github_saya_instagram_saya_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perusahaan', models.CharField(max_length=255)),
                ('tahun_mulai', models.CharField(max_length=255)),
                ('tahun_selesai', models.CharField(max_length=255)),
                ('posisi', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
