# Generated by Django 4.1.2 on 2022-10-26 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pendidikan_institusi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kemampuan',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='kemampuan',
            name='tingkatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tingkatankemampuan'),
        ),
    ]
