# Generated by Django 4.1.2 on 2022-10-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_kemampuan_logo_alter_kemampuan_tingkatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kerja',
            name='deskripsi',
        ),
        migrations.CreateModel(
            name='TugasKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tugas', models.CharField(max_length=255)),
                ('kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kerja')),
            ],
        ),
    ]
