# Generated by Django 4.1.2 on 2022-10-27 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_tugaskerja_kerja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentasiprojek',
            name='projek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumentasi_projek', to='app.projek'),
        ),
        migrations.AlterField(
            model_name='teknologiprojek',
            name='projek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teknologi_projek', to='app.projek'),
        ),
    ]
