# Generated by Django 4.1.2 on 2022-10-29 04:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_aktifitas_posisiprojek_alter_projek_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projek',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
